# -*- coding: utf-8 -*-
"""partedelproyecto

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ug9HmFxSGlZ5ZcO1LBBNAAWPZ40Zl8kt
"""

import pandas as pd
import matplotlib.pyplot as plt

data = {
    'Área Natural Protegida': ['Chancaybaños', 'Santiago Comaina', 'Cordillera Huayhuash', 'Sierra del Divisor', 'Río Nieva', 'Bosque de Zárate', 'Reserva Paisajística Cerro Khapia', 'Ancón'],
    'Superficie (ha)': [2628, 398449.44, 67589.76, 62234.62, 36348.3, 545.75, 18313.79, 2193.01]
}

df = pd.DataFrame(data)

fig, ax = plt.subplots(figsize=(10,6))
ax.barh(df['Área Natural Protegida'], df['Superficie (ha)'])
ax.set_xlabel('Superficie (ha)')
ax.set_title('Superficies de las Áreas Naturales Protegidas')